const fs = require('fs');
const path = require('path');

const root = process.cwd();
const b64 = (p) => fs.readFileSync(path.join(root, p)).toString('base64');
const files = {
  '/': { type: 'text/html; charset=utf-8', body: b64('index.html') },
  '/index.html': { type: 'text/html; charset=utf-8', body: b64('index.html') },
  '/login/': { type: 'text/html; charset=utf-8', body: b64('login/index.html') },
  '/login/index.html': { type: 'text/html; charset=utf-8', body: b64('login/index.html') },
  '/register/': { type: 'text/html; charset=utf-8', body: b64('register/index.html') },
  '/register/index.html': { type: 'text/html; charset=utf-8', body: b64('register/index.html') },
  '/admin/': { type: 'text/html; charset=utf-8', body: b64('admin/index.html') },
  '/admin/index.html': { type: 'text/html; charset=utf-8', body: b64('admin/index.html') },
  '/admin-key/': { type: 'text/html; charset=utf-8', body: b64('admin-key/index.html') },
  '/admin-key/index.html': { type: 'text/html; charset=utf-8', body: b64('admin-key/index.html') },
  '/forgot/': { type: 'text/html; charset=utf-8', body: b64('forgot/index.html') },
  '/forgot/index.html': { type: 'text/html; charset=utf-8', body: b64('forgot/index.html') },
  '/reset-password/': { type: 'text/html; charset=utf-8', body: b64('reset-password/index.html') },
  '/reset-password/index.html': { type: 'text/html; charset=utf-8', body: b64('reset-password/index.html') },
  '/verify-email/': { type: 'text/html; charset=utf-8', body: b64('verify-email/index.html') },
  '/verify-email/index.html': { type: 'text/html; charset=utf-8', body: b64('verify-email/index.html') },
  '/404/': { type: 'text/html; charset=utf-8', body: b64('404/index.html') },
  '/404/index.html': { type: 'text/html; charset=utf-8', body: b64('404/index.html') },
  '/403/': { type: 'text/html; charset=utf-8', body: b64('403/index.html') },
  '/403/index.html': { type: 'text/html; charset=utf-8', body: b64('403/index.html') },
  '/assets/app.js': { type: 'application/javascript; charset=utf-8', body: b64('assets/app.js') },
  '/assets/style.css': { type: 'text/css; charset=utf-8', body: b64('assets/style.css') },
  '/assets/logo.png': { type: 'image/png', body: b64('assets/logo.png') },
  '/assets/logo.svg': { type: 'image/svg+xml; charset=utf-8', body: b64('assets/logo.svg') },
  '/schema/d1.sql': { type: 'text/plain; charset=utf-8', body: b64('schema/d1.sql') },
  '/schema/01.sql': { type: 'text/plain; charset=utf-8', body: b64('schema/d1.sql') },
};

const worker = `// ZyraxForum single-file Cloudflare Worker for Dashboard paste deployment.
// 需要在 Worker Settings 里绑定 D1，变量名必须是 FORUM_DB。
// 可选变量：ADMIN_USERNAMES=admin，APP_BASE_URL=https://你的域名。

const STATIC_FILES_B64 = ${JSON.stringify(files)};
const SECURITY_HEADERS = { "x-content-type-options":"nosniff", "referrer-policy":"strict-origin-when-cross-origin", "permissions-policy":"camera=(), microphone=(), geolocation=()" };
function response(body,status=200,headers={}){return new Response(body,{status,headers:{...SECURITY_HEADERS,...headers}})}
function json(data,status=200,extraHeaders={}){return response(JSON.stringify(data),status,{"content-type":"application/json; charset=utf-8",...extraHeaders})}
async function readJson(request){try{return await request.json()}catch{return null}}
function uid(prefix="id"){const b=new Uint8Array(16);crypto.getRandomValues(b);return prefix+"_"+Date.now().toString(36)+"_"+[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
function now(){return Date.now()}
function normalizeUsername(value){return String(value||"").trim().split("").map(ch=>ch.trim()===""?"_":ch).join("")}
function validUsername(username){username=String(username||"");if(username.length<2||username.length>24)return false;for(const ch of username){const c=ch.charCodeAt(0);const ok=(c>=0x4e00&&c<=0x9fa5)||(c>=65&&c<=90)||(c>=97&&c<=122)||(c>=48&&c<=57)||ch==="_"||ch==="-";if(!ok)return false}return true}
function validEmail(email){email=String(email||"").trim();if(email.length<5||email.length>120)return false;if(email.includes(" ")||email.includes("\\n")||email.includes("\\r")||email.includes("\\t"))return false;const at=email.indexOf("@");const dot=email.lastIndexOf(".");return at>0&&dot>at+1&&dot<email.length-1}
function getClientIp(request){return request.headers.get("cf-connecting-ip")||request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown"}
function getCookie(request,name){const c=request.headers.get("cookie")||"";const p=c.split(";").map(x=>x.trim()).find(x=>x.startsWith(name+"="));return p?decodeURIComponent(p.slice(name.length+1)):""}
function sessionCookie(token,maxAgeSeconds=60*60*24*30,secure=true){const s=secure?"; Secure":"";return "cf_session="+encodeURIComponent(token)+"; Path=/; HttpOnly; SameSite=Lax"+s+"; Max-Age="+maxAgeSeconds}
function clearSessionCookie(secure=true){const s=secure?"; Secure":"";return "cf_session=; Path=/; HttpOnly; SameSite=Lax"+s+"; Max-Age=0"}
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function hexToBytes(hex){const s=String(hex||"");const out=new Uint8Array(Math.floor(s.length/2));for(let i=0;i<out.length;i++)out[i]=parseInt(s.slice(i*2,i*2+2),16);return out}
async function sha256Hex(input){return bytesToHex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input)))}
async function pbkdf2Hex(password,salt,iterations=100000){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);return bytesToHex(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:new TextEncoder().encode(salt),iterations},key,256))}
async function hashPassword(password,salt){const iterations=100000;return "pbkdf2_sha256$"+iterations+"$"+await pbkdf2Hex(password,salt,iterations)}
function timingSafeEqualHex(a,b){const aa=hexToBytes(a),bb=hexToBytes(b);if(aa.length!==bb.length)return false;let d=0;for(let i=0;i<aa.length;i++)d|=aa[i]^bb[i];return d===0}
async function verifyPassword(password,salt,storedHash){if(String(storedHash||"").startsWith("pbkdf2_sha256$")){const parts=storedHash.split("$");const iter=Number(parts[1]||100000);if(iter>100000)return false;return timingSafeEqualHex(await pbkdf2Hex(password,salt,iter),parts[2])}return timingSafeEqualHex(await sha256Hex(salt+":"+password+":cloudforum-server-v1"),storedHash)}
function isAdminUsername(env,username){const names=String(env.ADMIN_USERNAMES||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);names.push("admin","test");return names.includes(String(username||"").toLowerCase())}
function appBaseUrl(env,request){return env.APP_BASE_URL||new URL(request.url).origin}
async function cleanupExpiredSessions(env){await env.FORUM_DB.prepare("DELETE FROM sessions WHERE expires_at <= ?").bind(now()).run()}
async function getCurrentUser(env,request){const token=getCookie(request,"cf_session");if(!token)return null;await ensureUserPresence(env);const user=await env.FORUM_DB.prepare("SELECT users.id, users.username, users.email, users.email_verified, users.role, users.banned_at, users.banned_reason, users.last_seen_at, users.created_at FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token=? AND sessions.expires_at>?").bind(token,now()).first();if(user)await touchUserPresence(env,user.id);return user}
async function requireUser(env,request){const user=await getCurrentUser(env,request);if(!user)return{error:json({error:"UNAUTHENTICATED",message:"请先登录。"},401)};if(user.banned_at)return{error:json({error:"BANNED",message:"账号已封禁："+(user.banned_reason||"未填写原因")},403)};return{user}}
async function requireAdmin(env,request){const auth=await requireUser(env,request);if(auth.error)return auth;if(auth.user.role!=="admin"&&!isAdminUsername(env,auth.user.username))return{error:json({error:"FORBIDDEN",message:"\u53ea\u6709 admin \u548c test \u8d26\u53f7\u53ef\u4ee5\u8fdb\u5165\u7ba1\u7406\u9762\u677f\u3002"},403)};if(!(await verifyAdminGate(env,request,auth.user)))return{error:json({error:"ADMIN_LOCKED",message:"\u8bf7\u5148\u8f93\u5165\u7ba1\u7406\u5bc6\u94a5\u3002"},403)};return auth}
function adminSecret(env){return String(env.ADMIN_ACCESS_KEY||"adminkey12")}
async function adminGateSig(env,userId,ts){return await sha256Hex("admin-gate:"+adminSecret(env)+":"+userId+":"+ts)}
async function verifyAdminGate(env,request,user){const raw=getCookie(request,"admin_gate");if(!raw)return false;const parts=String(raw).split(".");if(parts.length!==2)return false;const ts=Number(parts[0]||0);if(!ts||now()-ts>1000*60*60*8)return false;const expected=await adminGateSig(env,user.id,ts);return timingSafeEqualHex(expected,parts[1])}
async function adminGateCookie(env,user,secure=true){const ts=now();const sig=await adminGateSig(env,user.id,ts);const s=secure?"; Secure":"";return "admin_gate="+encodeURIComponent(ts+"."+sig)+"; Path=/; HttpOnly; SameSite=Strict"+s+"; Max-Age="+(60*60*8)}
function clearAdminGateCookie(secure=true){const s=secure?"; Secure":"";return "admin_gate=; Path=/; HttpOnly; SameSite=Strict"+s+"; Max-Age=0"}
async function checkLoginRateLimit(env,key,windowMs=15*60*1000,maxAttempts=10){const since=now()-windowMs;await env.FORUM_DB.prepare("DELETE FROM login_attempts WHERE created_at < ?").bind(since).run();const row=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM login_attempts WHERE attempt_key=? AND created_at>=?").bind(key,since).first();return Number(row?.count||0)<maxAttempts}
async function recordLoginAttempt(env,key){await env.FORUM_DB.prepare("INSERT INTO login_attempts (id, attempt_key, created_at) VALUES (?, ?, ?)").bind(uid("la"),key,now()).run()}
async function clearLoginAttempts(env,key){await env.FORUM_DB.prepare("DELETE FROM login_attempts WHERE attempt_key=?").bind(key).run()}
async function sendMail(env,{to,subject,text}){if(env.RESEND_API_KEY&&env.MAIL_FROM){const res=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"authorization":"Bearer "+env.RESEND_API_KEY,"content-type":"application/json"},body:JSON.stringify({from:env.MAIL_FROM,to:[to],subject,text})});if(!res.ok){const detail=await res.text().catch(()=>"");throw new Error("MAIL_FAILED: "+detail.slice(0,240))}return{sent:true,provider:"resend"}}console.log("[ZyraxForum mail dev]\\nTO: "+to+"\\nSUBJECT: "+subject+"\\n"+text);return{sent:false,provider:"dev-log"}}
function makeEmailCode(){const b=new Uint32Array(1);crypto.getRandomValues(b);return String(b[0]%1000000).padStart(6,"0")}
function normalizeCode(code){return String(code||"").split("").filter(ch=>ch>="0"&&ch<="9").join("").slice(0,6)}
async function emailCodeHash(email,code){return await sha256Hex("register-email-code:"+String(email||"").toLowerCase()+":"+String(code||"")+":zyrax-v1")}
async function ensureRegisterCodes(env){await env.FORUM_DB.prepare("CREATE TABLE IF NOT EXISTS register_email_codes (id TEXT PRIMARY KEY, email TEXT NOT NULL COLLATE NOCASE, code_hash TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL, used_at INTEGER, ip_hash TEXT)").run();await env.FORUM_DB.prepare("CREATE INDEX IF NOT EXISTS idx_register_email_codes_email ON register_email_codes(email, created_at DESC)").run();await env.FORUM_DB.prepare("CREATE INDEX IF NOT EXISTS idx_register_email_codes_ip ON register_email_codes(ip_hash, created_at DESC)").run()}
async function ensureUserPresence(env){const cols=await env.FORUM_DB.prepare("PRAGMA table_info(users)").all();if(!(cols.results||[]).some(c=>c.name==="last_seen_at")){await env.FORUM_DB.prepare("ALTER TABLE users ADD COLUMN last_seen_at INTEGER").run()}}
async function touchUserPresence(env,userId){await ensureUserPresence(env);if(userId)await env.FORUM_DB.prepare("UPDATE users SET last_seen_at=? WHERE id=?").bind(now(),userId).run()}
async function ensurePostViews(env){const cols=await env.FORUM_DB.prepare("PRAGMA table_info(posts)").all();if(!(cols.results||[]).some(c=>c.name==="views")){await env.FORUM_DB.prepare("ALTER TABLE posts ADD COLUMN views INTEGER NOT NULL DEFAULT 0").run()}await env.FORUM_DB.prepare("CREATE TABLE IF NOT EXISTS post_views (post_id TEXT NOT NULL, viewer_key TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (post_id, viewer_key), FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE)").run();await env.FORUM_DB.prepare("CREATE INDEX IF NOT EXISTS idx_post_views_post_id ON post_views(post_id)").run()}
async function attachCounts(env,posts,currentUserId=""){if(!posts.length)return[];const ids=posts.map(p=>p.id),ph=ids.map(()=>"?").join(",");const comments=await env.FORUM_DB.prepare("SELECT post_id, COUNT(*) count FROM comments WHERE post_id IN ("+ph+") GROUP BY post_id").bind(...ids).all();const likes=await env.FORUM_DB.prepare("SELECT post_id, COUNT(*) count FROM post_likes WHERE post_id IN ("+ph+") GROUP BY post_id").bind(...ids).all();const liked=currentUserId?await env.FORUM_DB.prepare("SELECT post_id FROM post_likes WHERE user_id=? AND post_id IN ("+ph+")").bind(currentUserId,...ids).all():{results:[]};const cm=new Map((comments.results||[]).map(r=>[r.post_id,Number(r.count)]));const lm=new Map((likes.results||[]).map(r=>[r.post_id,Number(r.count)]));const ls=new Set((liked.results||[]).map(r=>r.post_id));return posts.map(p=>({...p,commentsCount:cm.get(p.id)||0,likesCount:lm.get(p.id)||0,likedByMe:ls.has(p.id)}))}
function requireDb(env){if(!env.FORUM_DB)return json({error:"D1_NOT_BOUND",message:"缺少 D1 绑定 FORUM_DB。请在 Worker Settings -> Bindings 里绑定 D1，变量名 FORUM_DB。"},500);return null}
async function apiHealth(env){const missing=requireDb(env);if(missing)return missing;try{const row=await env.FORUM_DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='users'").first();return json({ok:!!row,d1Bound:true,usersTable:!!row,message:row?"D1 正常。":"D1 已绑定，但还没执行 schema/d1.sql。可打开 /schema/d1.sql 复制初始化 SQL。"})}catch(err){return json({ok:false,d1Bound:true,error:"D1_ERROR",message:String(err&&err.message||err)},500)}}
async function apiSession(env,request){return json({user:await getCurrentUser(env,request)})}
async function apiStats(env){const users=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM users").first();const posts=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM posts").first();const comments=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM comments").first();return json({users:Number(users.count||0),posts:Number(posts.count||0),comments:Number(comments.count||0)})}
async function apiSendRegisterCode(env,request){await ensureRegisterCodes(env);const body=await readJson(request);const email=String(body?.email||"").trim().toLowerCase();if(!validEmail(email))return json({error:"BAD_EMAIL",message:"\u90ae\u7bb1\u683c\u5f0f\u4e0d\u6b63\u786e\u3002"},400);const exists=await env.FORUM_DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first();if(exists)return json({error:"EMAIL_EXISTS",message:"\u8be5\u90ae\u7bb1\u5df2\u7ecf\u6ce8\u518c\u3002"},409);const ts=now(),since=ts-10*60*1000,ipHash=await sha256Hex(getClientIp(request));await env.FORUM_DB.prepare("DELETE FROM register_email_codes WHERE expires_at < ? OR used_at IS NOT NULL").bind(ts-24*60*60*1000).run();const emailCount=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM register_email_codes WHERE email=? AND created_at>=?").bind(email,since).first();const ipCount=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM register_email_codes WHERE ip_hash=? AND created_at>=?").bind(ipHash,since).first();if(Number(emailCount?.count||0)>=5||Number(ipCount?.count||0)>=10)return json({error:"RATE_LIMITED",message:"\u9a8c\u8bc1\u7801\u53d1\u9001\u592a\u9891\u7e41\uff0c10 \u5206\u949f\u540e\u518d\u8bd5\u3002"},429);const code=makeEmailCode(),codeHash=await emailCodeHash(email,code);await env.FORUM_DB.prepare("INSERT INTO register_email_codes (id, email, code_hash, attempt_count, created_at, expires_at, ip_hash) VALUES (?, ?, ?, 0, ?, ?, ?)").bind(uid("ec"),email,codeHash,ts,ts+10*60*1000,ipHash).run();try{const mail=await sendMail(env,{to:email,subject:"ZyraxForum \u6ce8\u518c\u9a8c\u8bc1\u7801",text:"\u4f60\u7684 ZyraxForum \u6ce8\u518c\u9a8c\u8bc1\u7801\u662f\uff1a"+code+"\\n\\n10 \u5206\u949f\u5185\u6709\u6548\u3002\u5982\u679c\u4e0d\u662f\u4f60\u672c\u4eba\u64cd\u4f5c\uff0c\u8bf7\u5ffd\u7565\u8fd9\u5c01\u90ae\u4ef6\u3002"});return json({ok:true,message:mail.provider==="dev-log"?"\u9a8c\u8bc1\u7801\u5df2\u751f\u6210\u3002\u5f53\u524d\u672a\u914d\u7f6e\u90ae\u4ef6\u670d\u52a1\uff0c\u5df2\u8fd4\u56de devCode \u65b9\u4fbf\u6d4b\u8bd5\u3002":"\u9a8c\u8bc1\u7801\u5df2\u53d1\u9001\uff0c\u8bf7\u67e5\u770b\u90ae\u7bb1\u3002",devCode:mail.provider==="dev-log"?code:undefined})}catch(err){return json({error:"MAIL_FAILED",message:String(err&&err.message||err)},502)}}
async function apiRegister(env,request){await ensureRegisterCodes(env);const body=await readJson(request);const username=normalizeUsername(body?.username);const email=String(body?.email||"").trim().toLowerCase();const password=String(body?.password||"");const verificationCode=normalizeCode(body?.verificationCode);await cleanupExpiredSessions(env);if(!validUsername(username))return json({error:"BAD_USERNAME",message:"Username must be 2-24 chars: Chinese, letters, numbers, _ or -."},400);if(!validEmail(email))return json({error:"BAD_EMAIL",message:"Invalid email address."},400);if(verificationCode.length!==6)return json({error:"BAD_CODE",message:"Enter the 6-digit email verification code."},400);if(password.length<8)return json({error:"BAD_PASSWORD",message:"Password must be at least 8 characters."},400);const exists=await env.FORUM_DB.prepare("SELECT id FROM users WHERE username = ? OR email = ?").bind(username,email).first();if(exists)return json({error:"USER_EXISTS",message:"Username or email already exists."},409);const codeRow=await env.FORUM_DB.prepare("SELECT id, code_hash, attempt_count, expires_at FROM register_email_codes WHERE email=? AND used_at IS NULL ORDER BY created_at DESC LIMIT 1").bind(email).first();if(!codeRow||Number(codeRow.expires_at||0)<now())return json({error:"CODE_EXPIRED",message:"Code does not exist or has expired. Send a new one."},400);if(Number(codeRow.attempt_count||0)>=5)return json({error:"CODE_LOCKED",message:"Too many wrong attempts. Send a new code."},429);const inputHash=await emailCodeHash(email,verificationCode);if(!timingSafeEqualHex(inputHash,codeRow.code_hash)){await env.FORUM_DB.prepare("UPDATE register_email_codes SET attempt_count=attempt_count+1 WHERE id=?").bind(codeRow.id).run();return json({error:"BAD_CODE",message:"Incorrect verification code."},400)}const userId=uid("u"),salt=uid("salt"),passwordHash=await hashPassword(password,salt),role=isAdminUsername(env,username)?"admin":"user",createdAt=now(),token=uid("sess"),expiresAt=createdAt+1000*60*60*24*30;await env.FORUM_DB.batch([env.FORUM_DB.prepare("INSERT INTO users (id, username, email, email_verified, password_hash, salt, role, last_seen_at, created_at) VALUES (?, ?, ?, 1, ?, ?, ?, ?, ?)").bind(userId,username,email,passwordHash,salt,role,createdAt,createdAt),env.FORUM_DB.prepare("UPDATE register_email_codes SET used_at=? WHERE id=?").bind(createdAt,codeRow.id),env.FORUM_DB.prepare("INSERT INTO sessions (token, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)").bind(token,userId,createdAt,expiresAt)]);const secure=new URL(request.url).protocol==="https:";return json({user:{id:userId,username,email,email_verified:1,role,last_seen_at:createdAt,created_at:createdAt}},201,{"set-cookie":sessionCookie(token,undefined,secure)})}
async function apiLogin(env,request){const body=await readJson(request);const username=String(body?.username||"").trim();const password=String(body?.password||"");const attemptKey=getClientIp(request)+":"+username.toLowerCase();await cleanupExpiredSessions(env);if(!(await checkLoginRateLimit(env,attemptKey)))return json({error:"RATE_LIMITED",message:"登录尝试太多，15 分钟后再试。"},429);const user=await env.FORUM_DB.prepare("SELECT id, username, email, email_verified, role, banned_at, banned_reason, password_hash, salt, created_at FROM users WHERE username = ? OR email = ?").bind(username,username.toLowerCase()).first();if(!user||!(await verifyPassword(password,user.salt,user.password_hash))){await recordLoginAttempt(env,attemptKey);return json({error:"BAD_LOGIN",message:"账号或密码错误。"},401)}if(user.banned_at)return json({error:"BANNED",message:"账号已封禁："+(user.banned_reason||"未填写原因")},403);await clearLoginAttempts(env,attemptKey);const token=uid("sess"),createdAt=now(),expiresAt=createdAt+1000*60*60*24*30;await env.FORUM_DB.prepare("INSERT INTO sessions (token, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)").bind(token,user.id,createdAt,expiresAt).run();await touchUserPresence(env,user.id);const secure=new URL(request.url).protocol==="https:";return json({user:{id:user.id,username:user.username,email:user.email,email_verified:user.email_verified,role:user.role,last_seen_at:now(),created_at:user.created_at}},200,{"set-cookie":sessionCookie(token,undefined,secure)})}
async function apiLogout(env,request){const token=getCookie(request,"cf_session");if(token)await env.FORUM_DB.prepare("DELETE FROM sessions WHERE token = ?").bind(token).run();const secure=new URL(request.url).protocol==="https:";return json({ok:true},200,{"set-cookie":clearSessionCookie(secure)})}
async function apiPostsList(env,request){await ensurePostViews(env);const url=new URL(request.url);const q=(url.searchParams.get("q")||"").trim();const category=(url.searchParams.get("category")||"全部").trim();const sort=url.searchParams.get("sort")||"new";const currentUser=await getCurrentUser(env,request);let sql="SELECT posts.id, posts.title, posts.category, posts.body, COALESCE(posts.views,0) AS views, posts.created_at, posts.updated_at, users.username AS author, users.id AS author_id FROM posts JOIN users ON users.id = posts.author_id";const where=[],binds=[];if(category&&category!=="全部"){where.push("posts.category = ?");binds.push(category)}if(q){where.push("(posts.title LIKE ? OR posts.body LIKE ? OR users.username LIKE ?)");binds.push("%"+q+"%","%"+q+"%","%"+q+"%")}if(where.length)sql+=" WHERE "+where.join(" AND ");if(sort==="views")sql+=" ORDER BY COALESCE(posts.views,0) DESC, posts.created_at DESC";else if(sort==="hot")sql+=" ORDER BY (SELECT COUNT(*) FROM post_likes WHERE post_likes.post_id = posts.id) DESC, posts.created_at DESC";else if(sort==="comment")sql+=" ORDER BY (SELECT COUNT(*) FROM comments WHERE comments.post_id = posts.id) DESC, posts.created_at DESC";else sql+=" ORDER BY posts.created_at DESC";sql+=" LIMIT 100";const rows=await env.FORUM_DB.prepare(sql).bind(...binds).all();return json({posts:await attachCounts(env,rows.results||[],currentUser?.id||"")})}
async function apiCreatePost(env,request){await ensurePostViews(env);const auth=await requireUser(env,request);if(auth.error)return auth.error;const body=await readJson(request);const title=String(body?.title||"").trim();const category=String(body?.category||"").trim();const content=String(body?.body||"").trim();const allowed=new Set(["公告","技术","资源","闲聊","反馈"]);if(title.length<2||title.length>80)return json({error:"BAD_TITLE",message:"标题需 2-80 字。"},400);if(!allowed.has(category))return json({error:"BAD_CATEGORY",message:"板块无效。"},400);if(content.length<2||content.length>3000)return json({error:"BAD_BODY",message:"内容需 2-3000 字。"},400);const id=uid("p"),ts=now();await env.FORUM_DB.prepare("INSERT INTO posts (id, author_id, title, category, body, views, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 0, ?, ?)").bind(id,auth.user.id,title,category,content,ts,ts).run();return json({post:{id,author:auth.user.username,author_id:auth.user.id,title,category,body:content,views:0,created_at:ts,updated_at:ts,commentsCount:0,likesCount:0,likedByMe:false}},201)}
async function apiPostDetail(env,request,id){await ensurePostViews(env);const exists=await env.FORUM_DB.prepare("SELECT id FROM posts WHERE id=?").bind(id).first();if(!exists)return json({error:"NOT_FOUND",message:"\u4e3b\u9898\u4e0d\u5b58\u5728\u3002"},404);const currentUser=await getCurrentUser(env,request);const viewerKey=currentUser?"user:"+currentUser.id:"ip:"+await sha256Hex(getClientIp(request));const seen=await env.FORUM_DB.prepare("SELECT post_id FROM post_views WHERE post_id=? AND viewer_key=?").bind(id,viewerKey).first();if(!seen){await env.FORUM_DB.batch([env.FORUM_DB.prepare("INSERT OR IGNORE INTO post_views (post_id, viewer_key, created_at) VALUES (?, ?, ?)").bind(id,viewerKey,now()),env.FORUM_DB.prepare("UPDATE posts SET views=(SELECT COUNT(*) FROM post_views WHERE post_id=?) WHERE id=?").bind(id,id)])}const row=await env.FORUM_DB.prepare("SELECT posts.id, posts.title, posts.category, posts.body, COALESCE(posts.views,0) AS views, posts.created_at, posts.updated_at, users.username AS author, users.id AS author_id FROM posts JOIN users ON users.id=posts.author_id WHERE posts.id=?").bind(id).first();if(!row)return json({error:"NOT_FOUND",message:"主题不存在。"},404);const arr=await attachCounts(env,[row],currentUser?.id||"");const comments=await env.FORUM_DB.prepare("SELECT comments.id, comments.body, comments.created_at, users.username AS author, users.id AS author_id FROM comments JOIN users ON users.id=comments.author_id WHERE comments.post_id=? ORDER BY comments.created_at ASC").bind(id).all();return json({post:arr[0],comments:comments.results||[]})}
async function apiDeletePost(env,request,id){const auth=await requireUser(env,request);if(auth.error)return auth.error;const post=await env.FORUM_DB.prepare("SELECT author_id FROM posts WHERE id=?").bind(id).first();if(!post)return json({error:"NOT_FOUND",message:"主题不存在。"},404);if(post.author_id!==auth.user.id&&auth.user.role!=="admin")return json({error:"FORBIDDEN",message:"只能删除自己的主题。"},403);await env.FORUM_DB.prepare("DELETE FROM posts WHERE id=?").bind(id).run();return json({ok:true})}
async function apiComment(env,request,id){const auth=await requireUser(env,request);if(auth.error)return auth.error;const body=await readJson(request);const content=String(body?.body||"").trim();if(content.length<1||content.length>500)return json({error:"BAD_COMMENT",message:"回复需 1-500 字。"},400);const post=await env.FORUM_DB.prepare("SELECT id FROM posts WHERE id=?").bind(id).first();if(!post)return json({error:"NOT_FOUND",message:"主题不存在。"},404);const cid=uid("c"),ts=now();await env.FORUM_DB.prepare("INSERT INTO comments (id, post_id, author_id, body, created_at) VALUES (?, ?, ?, ?, ?)").bind(cid,id,auth.user.id,content,ts).run();return json({comment:{id:cid,post_id:id,author_id:auth.user.id,author:auth.user.username,body:content,created_at:ts}},201)}
async function apiLike(env,request,id){const auth=await requireUser(env,request);if(auth.error)return auth.error;const existing=await env.FORUM_DB.prepare("SELECT post_id FROM post_likes WHERE post_id=? AND user_id=?").bind(id,auth.user.id).first();if(existing)await env.FORUM_DB.prepare("DELETE FROM post_likes WHERE post_id=? AND user_id=?").bind(id,auth.user.id).run();else await env.FORUM_DB.prepare("INSERT INTO post_likes (post_id, user_id, created_at) VALUES (?, ?, ?)").bind(id,auth.user.id,now()).run();const row=await env.FORUM_DB.prepare("SELECT COUNT(*) count FROM post_likes WHERE post_id=?").bind(id).first();return json({liked:!existing,likesCount:Number(row.count||0)})}
async function apiForgot(env,request){const body=await readJson(request);const email=String(body?.email||"").trim().toLowerCase();if(!validEmail(email))return json({error:"BAD_EMAIL",message:"邮箱格式不正确。"},400);const user=await env.FORUM_DB.prepare("SELECT id, email FROM users WHERE email=?").bind(email).first();if(!user)return json({ok:true,message:"如果邮箱存在，重置链接已发送。"});const token=uid("reset"),ts=now();await env.FORUM_DB.prepare("INSERT INTO password_resets (token, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)").bind(token,user.id,ts,ts+1000*60*30).run();const resetUrl=appBaseUrl(env,request)+"/reset-password/?token="+encodeURIComponent(token);const mail=await sendMail(env,{to:email,subject:"重置你的 ZyraxForum 密码",text:"打开链接重置密码：\\n"+resetUrl+"\\n\\n链接 30 分钟内有效。"});return json({ok:true,message:"如果邮箱存在，重置链接已发送。",devResetUrl:mail.provider==="dev-log"?resetUrl:undefined})}
async function apiReset(env,request){const body=await readJson(request);const token=String(body?.token||"");const password=String(body?.password||"");if(password.length<8)return json({error:"BAD_PASSWORD",message:"密码至少 8 位。"},400);const row=await env.FORUM_DB.prepare("SELECT token, user_id FROM password_resets WHERE token=? AND used_at IS NULL AND expires_at>?").bind(token,now()).first();if(!row)return json({error:"BAD_TOKEN",message:"重置链接无效或已过期。"},400);const salt=uid("salt"),passwordHash=await hashPassword(password,salt);await env.FORUM_DB.batch([env.FORUM_DB.prepare("UPDATE users SET password_hash=?, salt=? WHERE id=?").bind(passwordHash,salt,row.user_id),env.FORUM_DB.prepare("UPDATE password_resets SET used_at=? WHERE token=?").bind(now(),token),env.FORUM_DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(row.user_id)]);return json({ok:true,message:"密码已重置，请重新登录。"})}
async function apiAdminUnlock(env,request){const auth=await requireUser(env,request);if(auth.error)return auth.error;if(auth.user.role!=="admin"&&!isAdminUsername(env,auth.user.username))return json({error:"FORBIDDEN",message:"\u8d26\u53f7\u6ca1\u6709\u7ba1\u7406\u6743\u9650\u3002"},403);const key="admin-key:"+await sha256Hex(getClientIp(request)+":"+auth.user.id);if(!(await checkLoginRateLimit(env,key,30*60*1000,5)))return json({error:"ADMIN_KEY_LOCKED",message:"\u9519\u8bef\u6b21\u6570\u592a\u591a\uff0c30 \u5206\u949f\u540e\u518d\u8bd5\u3002"},429);const body=await readJson(request);const input=String(body?.key||"");const ok=timingSafeEqualHex(await sha256Hex("admin-key-input:"+input),await sha256Hex("admin-key-input:"+adminSecret(env)));if(!ok){await recordLoginAttempt(env,key);return json({error:"BAD_ADMIN_KEY",message:"\u7ba1\u7406\u5bc6\u94a5\u9519\u8bef\u3002"},403)}await clearLoginAttempts(env,key);const secure=new URL(request.url).protocol==="https:";return json({ok:true},200,{"set-cookie":await adminGateCookie(env,auth.user,secure)})}
async function apiAdminUsers(env,request){const auth=await requireAdmin(env,request);if(auth.error)return auth.error;await ensureUserPresence(env);const onlineSince=now()-5*60*1000;const rows=await env.FORUM_DB.prepare("SELECT users.id, users.username, users.email, users.email_verified, users.role, users.banned_at, users.banned_reason, users.last_seen_at, users.created_at, CASE WHEN users.last_seen_at>=? AND EXISTS (SELECT 1 FROM sessions WHERE sessions.user_id=users.id AND sessions.expires_at>?) THEN 1 ELSE 0 END AS online FROM users ORDER BY users.created_at DESC LIMIT 200").bind(onlineSince,now()).all();return json({users:rows.results||[]})}
async function apiBan(env,request,id){const auth=await requireAdmin(env,request);if(auth.error)return auth.error;if(id===auth.user.id)return json({error:"SELF_BAN",message:"不能封禁自己。"},400);const body=await readJson(request);const reason=String(body?.reason||"违反社区规则").slice(0,160);await env.FORUM_DB.prepare("UPDATE users SET banned_at=?, banned_reason=? WHERE id=?").bind(now(),reason,id).run();await env.FORUM_DB.prepare("DELETE FROM sessions WHERE user_id=?").bind(id).run();return json({ok:true})}
async function apiUnban(env,request,id){const auth=await requireAdmin(env,request);if(auth.error)return auth.error;await env.FORUM_DB.prepare("UPDATE users SET banned_at=NULL, banned_reason=NULL WHERE id=?").bind(id).run();return json({ok:true})}
function cleanApiPath(pathname){let path=pathname||"/";while(path.length>1&&path.endsWith("/"))path=path.slice(0,-1);return path||"/"}
async function handleApi(request,env){const url=new URL(request.url),path=cleanApiPath(url.pathname),method=request.method.toUpperCase();if(path==="/api/health")return apiHealth(env);const missing=requireDb(env);if(missing)return missing;if(path==="/api/session"&&method==="GET")return apiSession(env,request);if(path==="/api/stats"&&method==="GET")return apiStats(env);if(path==="/api/auth/send-register-code"&&method==="POST")return apiSendRegisterCode(env,request);if(path==="/api/auth/register"&&method==="POST")return apiRegister(env,request);if(path==="/api/auth/login"&&method==="POST")return apiLogin(env,request);if(path==="/api/auth/logout"&&method==="POST")return apiLogout(env,request);if(path==="/api/auth/verify-email"&&method==="GET")return json({ok:true,message:"\u90ae\u7bb1\u9a8c\u8bc1\u5df2\u5173\u95ed\uff0c\u8d26\u53f7\u6ce8\u518c\u540e\u76f4\u63a5\u53ef\u7528\u3002"});if(path==="/api/auth/forgot-password"&&method==="POST")return apiForgot(env,request);if(path==="/api/auth/password-reset/confirm"&&method==="POST")return apiReset(env,request);if(path==="/api/posts"&&method==="GET")return apiPostsList(env,request);if(path==="/api/posts"&&method==="POST")return apiCreatePost(env,request);const parts=path.split("/").filter(Boolean);if(parts.length===3&&parts[0]==="api"&&parts[1]==="posts"){const id=decodeURIComponent(parts[2]);if(method==="GET")return apiPostDetail(env,request,id);if(method==="DELETE")return apiDeletePost(env,request,id)}if(parts.length===4&&parts[0]==="api"&&parts[1]==="posts"&&parts[3]==="comments"&&method==="POST")return apiComment(env,request,decodeURIComponent(parts[2]));if(parts.length===4&&parts[0]==="api"&&parts[1]==="posts"&&parts[3]==="like"&&method==="POST")return apiLike(env,request,decodeURIComponent(parts[2]));if(path==="/api/admin/unlock"&&method==="POST")return apiAdminUnlock(env,request);if(path==="/api/admin/users"&&method==="GET")return apiAdminUsers(env,request);if(parts.length===5&&parts[0]==="api"&&parts[1]==="admin"&&parts[2]==="users"&&parts[4]==="ban"){const id=decodeURIComponent(parts[3]);if(method==="POST")return apiBan(env,request,id);if(method==="DELETE")return apiUnban(env,request,id)}return json({error:"NOT_FOUND",message:"API route not found."},404)}
function decodeB64(b64){const bin=atob(b64);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}
async function serveStatic(request,env){const url=new URL(request.url);let path=url.pathname;const isAdminPath=path==="/admin"||path==="/admin/"||path==="/admin/index.html";if(isAdminPath){if(!env.FORUM_DB)return response("Admin requires FORUM_DB binding.",500,{"content-type":"text/plain; charset=utf-8"});const user=await getCurrentUser(env,request);if(!user)return Response.redirect(url.origin+"/login/?next="+encodeURIComponent("/admin/"),302);if(!(user.role==="admin"||isAdminUsername(env,user.username))){const item=STATIC_FILES_B64["/403/"]||STATIC_FILES_B64["/403/index.html"]||STATIC_FILES_B64["/404/"];return response(decodeB64(item.body),403,{"content-type":item.type})}if(!(await verifyAdminGate(env,request,user))){const item=STATIC_FILES_B64["/admin-key/"];return response(decodeB64(item.body),200,{"content-type":item.type})}}if(path==="/admin-key"||path==="/admin-key/"){const item=STATIC_FILES_B64["/admin-key/"];return response(decodeB64(item.body),200,{"content-type":item.type})}if(path==="/404"||path==="/404/"){const item=STATIC_FILES_B64["/404/"];return response(decodeB64(item.body),404,{"content-type":item.type})}if(path==="/403"||path==="/403/"){const item=STATIC_FILES_B64["/403/"]||STATIC_FILES_B64["/403/index.html"]||STATIC_FILES_B64["/404/"];return response(decodeB64(item.body),403,{"content-type":item.type})}const parts=path.split("/").filter(Boolean);if(parts.length===3&&parts[0]==="t")path="/index.html";const item=STATIC_FILES_B64[path]||STATIC_FILES_B64[path+"/"];if(!item){const fallback=STATIC_FILES_B64["/404/"]||STATIC_FILES_B64["/404/index.html"];return response(decodeB64(fallback.body),404,{"content-type":fallback.type})}return response(decodeB64(item.body),200,{"content-type":item.type})}

export default{async fetch(request,env){try{const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return await handleApi(request,env);return await serveStatic(request,env)}catch(err){return json({error:"WORKER_EXCEPTION",message:String(err&&err.message||err),hint:"访问 /api/health 看 D1 绑定和表状态。"},500)}}};
`;

fs.writeFileSync(path.join(root, 'worker-dashboard.js'), worker, 'utf8');
console.log(path.join(root, 'worker-dashboard.js'));
console.log('bytes=' + Buffer.byteLength(worker));






